### PR TITLE
Added ldap mount path

### PR DESCRIPTION
**Pull request by BenCamareno**
This update allows the user to enter the ldap mount path they want to authenticate with.

### CODE REVIEW

**Comment by BenCamareno** [comment]
image

**Comment by dmitry-treskunov** [comment]
Hi, thanks for the PR. If I'm not mistaken this change will break all existing Vault connections where the Path is not explicitly defined. I think it makes sense to make the Path field optional and use the "ldap" value as the default one

**Comment by BenCamareno** [comment]
@dmitry-treskunov This has been updated now. Thanks.

**Comment by VladRassokhin** [comment]
@dmitry-treskunov please reformat jsp file back after merging.

**Pull request merged**
